### ISSUE TITLE
Remove dependency on kindiana's fork of Actix

### ISSUE THREAD

**Issue by jkilpatr** [althea-mesh/althea_rs#217]
https://github.com/Kimundi/owning-ref-rs/pull/44

No longer needed.

**Comment by mpapierski** [comment]
I revieved this issue and turns out its not that simple. While Kimundi/owning-ref-rs#44 is fixed, there is still dependency on `actix::actors::Mocker` which for some reason is still commended out in upstream. See actix/actix#123 for more details. I pinged maintainers and once there is a response from them I'll volunteer to either split that PR into smaller parts (i.e. 1. add mocker 2. add additional APIs). Eventually without response we can put `mocker.rs` from actix into `actix_utils`. 

For now I'll close my PR and I'll pick it up once there is a progress upstream.

**Comment by mpapierski** [comment]
Update:

Actix maintainers were really helpful and responded in minutes. Upstream fixes are merged in so we can move forward with this.
