### ISSUE TITLE
Obscure Babel Int Parsing error

### ISSUE THREAD

**Issue by jkilpatr** [althea-mesh/althea_rs#321]
Observed when first flashing 10RC4 by Josh and I, went away after reboot, can't be identified by Adam 

Main symptoms include the neighbours endpoint giving a 500 and generally bad behavior as babel failed to parse routes. 

I've assigned Adam to make a basic pull request to log route parsing in more detail with the hope of capturing it in the future.

**Comment by JoshuaPCarr** [comment]
Further down the rabbit hole:

Initially believed an issue with the GLB1300. Culprit on my end turned out to be an N600 setup as gateway. Connecting another N600 as router (no exit) added a single neighbor to the N600 router (it saw the GLB, but not the N600Gateway)and the neighbors GLB (saw the N600 router, not n600 gateway). Rebooted N600 Gateway and all devices see their neighbors and connect to exit.

First Topology (only 2 devices)
n600 Gateway: Exit registered. Connecting to Exit Servers. Internet Accessible. No Peers
GLB: No exit registered. No Connections to Exit Servers. No Peers

Second Topology (3 devices)
n600 Gateway: Exit registered. Connecting to Exit Servers. Internet Accessible. No Peers
GLB: No exit registered. No Connections to Exit Servers. Sees N600 Router.
N600 Router: Exit Registered. No Connection to Exit Server. Sees GLB

Still attempting to reproduce deliberately.
